### ISSUE TITLE
how i start the game ?

### ISSUE THREAD

**Issue by anarerdene** [timhaley94/holdem#104]
### Background

Summary of the feature

### Current Behavior

What it does:

  -
  -
  -

### Proposed Behavior

What it should do:

  -
  -
  -

### Open Questions

If applicable...

**Comment by timhaley94** [comment]
@anarerdene this repository is still a work in progress. Once we get to a version 1, then you'll be able to play a game by running the code base locally, or through a public website. If you want to contribute features to help us get closer to that goal, feel free to check out some of the other open issues.
