### ISSUE TITLE
unable to assess backend http://localhost:8080/users

### ISSUE THREAD

**Issue by prabhatpankaj** [timhaley94/holdem#140]
<img width="942" alt="Screenshot 2020-12-09 at 8 10 38 AM" src="https://user-images.githubusercontent.com/20439273/101567029-17dc8c80-39f6-11eb-897b-01328fa49a52.png">

<img width="1362" alt="Screenshot 2020-12-09 at 8 12 16 AM" src="https://user-images.githubusercontent.com/20439273/101567739-663e5b00-39f7-11eb-8716-53d3ce5e52e4.png">

I tried to run it via docker-compose .. still unreachable to localhost:8080 .

did I miss something?

**Comment by timhaley94** [comment]
Hey thanks for the interest. I've been primarily working on infrastructure stuff so potentially I broke the dev environment. I'll check it out now.

**Comment by timhaley94** [comment]
@prabhatpankaj I changed the port the server uses from 8080 to 80. The local load balancer still uses 8080. Maybe you just pulled down main on a bad commit? Maybe pull from main and try again.
<img width="1107" alt="Screen Shot 2020-12-10 at 10 20 15 PM" src="https://user-images.githubusercontent.com/14980932/101857687-14e8b580-3b36-11eb-85cf-d4ffec545fe8.png">

**Comment by timhaley94** [comment]
Also, you can run `./scripts up` from the root of the directory if you want to run it as a distributed system (two servers instead of just one).

**Comment by prabhatpankaj** [comment]
Hi, Thanks @timhaley94. I will check it again.

As I can see you have created a dev( docker-compose ) and prod ( terraform ) environment, But for debugging and enhancing code, need to have a local environment ( client, server, mongo, Redis, etc without docker-compose ), I have created such an environment. if you allow me, I can create a pull request.

**Comment by timhaley94** [comment]
@prabhatpankaj yeah the idea was to use docker compose to allow people easily spin up a local dev environment without needing to manually configure all the individual pieces (particularly redis and mongo). At the moment, the docker compose file is only used locally.

However, you're more than welcome to open a pull request if you have another idea!

**Comment by timhaley94** [comment]
@prabhatpankaj relooking at your original picture, you are on holdemhounds.com, so that's definitely not going to hit localhost:8080. If you go to holdemhounds.com now, it can talk to the server after some recent PRs I pushed.
