### ISSUE TITLE
Game rule Implementation 

### ISSUE THREAD

**Issue by prabhatpankaj** [timhaley94/holdem#150]
Hi As per screens, It displaying 'Hi from Game'

In order to play the game with players, what should be the next step?

<img width="1434" alt="Screenshot 2020-12-15 at 2 01 28 PM" src="https://user-images.githubusercontent.com/20439273/102190542-2dfab900-3ede-11eb-9c31-15df529ec35e.png">

**Comment by timhaley94** [comment]
@prabhatpankaj 😄 

Yeah, the "hi" is just a placeholder. So, I don't know how easy it easy to explain what needs to be on this screen. Laura, the designer working on this project, is working on wire frames. Once the wire frames are done, we can make more detailed issues explaining the next steps.

Although if you look at prod right now, you'll see there are some more detailed placeholders that just "Hi from game".

**Comment by timhaley94** [comment]
@prabhatpankaj if you're looking for something to work on, once I have the wire frames I can share, I'll write some detailed tickets. I'm going to be working on lots of things over the next two weeks, but I'll be more active on here documenting what I'm working on.

**Comment by prabhatpankaj** [comment]
Hi, @timhaley94 thanks for the detailed information.
Will be waiting for the next update ...

**Comment by timhaley94** [comment]
I'm turning this issue into a milestone:
https://github.com/timhaley94/holdem/milestone/8

^I will open a series of issues as part of that milestone which document all the work that needs to be done to ship the game interactions.
