### ISSUE TITLE
Connect game engine

### ISSUE THREAD

**Issue by timhaley94** [timhaley94/holdem#8]
Here's a prebuilt game engine. We need to stand this server up and have our server talk to it, or find a way to run the code directly.

https://github.com/brunoscopelliti/poker-holdem-engine

**Comment by eliaswood** [comment]
Do you know offhand which would be more efficient?

**Comment by timhaley94** [comment]
@eliaswood financially calling their code directly instead of needing to stand up an API is more efficient because we won't have to pay for two more ec2 instances and a load balancer. It may be a lot of work to change their code to let us do that. We'd have to fork their repo and make a custom version.

**Comment by timhaley94** [comment]
We could also look for other javascript or c libraries (node.js has interop with c, so c libraries work as well). When I searched on npm there were plenty of options, they just don't seem very well maintained.

**Comment by timhaley94** [comment]
Interestingly, way back I got about 80% done writing a five card draw engine in elixir. Extending it to texas hold'em wouldn't be too hard, but it would be better if we didn't have to maintain the engine.

https://github.com/timhaley94/five_card_draw

**Comment by timhaley94** [comment]
@Jacob-c-ellis relevant to you as well.

**Comment by eliaswood** [comment]
How much are we talking for maintaining? I get the ideal of not having to at all but the basic js logic doesn't seem like it would be affected too much by future js updates

**Comment by timhaley94** [comment]
@eliaswood yeah hopefully it wouldn't change. I mean if we write an engine it ain't the worst thing in the world.
